# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Basics
  items:
    - label: "Parameters"
      link: "/basics/parameters"
- label: Android
  items:
    - label: "SDK Installation"
      link: "/android/sdk-installation"
    - label: "SDK Implementation"
      link: "/android/sdk-implementation"
    - label: "StartCheckoutByURL"
      link: "/android/start-checkout-by-url"
    - label: "StartCheckoutByParams"
      link: "/android/start-checkout-by-params"
- label: iOS
  items:
    - label: "TODO"
      link: "/ios/todo"
- label: Extras
  items:
    - label: "Languages"
      link: "/extras/language"
    - label: "Merchant Logo Image"
      link: "/extras/logo-image"
    - label: "Activity result"
      link: "/extras/activity-result"
- label: More
  items:
    - label: Paylivre
      link: https://www.paylivre.com/
    - label: "Paylivre twitter"
      link: https://twitter.com/Paylivre
    - label: "Project's GitHub"
      link: https://github.com/paylivre/sdk-gateway-mobile-docs
