# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Basics
  items:
    - label: "Creating docs"
      link: "/basics/creating-docs"
    - label: "Navigation"
      link: "/basics/navigation"
- label: Android
  items:
    - label: "Getting Started"
      link: "/android/getting-started"
    - label: "Push Notifications"
      link: "/android/push-notifications"
    - label: "Java and Kotlin display"
      link: "/android/kotlin-java-display"
- label: iOS
  items:
    - label: "Getting Started"
      link: "/ios/getting-started"
    - label: "Push Notifications"
      link: "/ios/push-notifications"
- label: More
  items:
    - label: Paylivre
      link: https://www.paylivre.com/
    - label: "Paylivre twitter"
      link: https://twitter.com/Paylivre
    - label: "Project's GitHub"
      link: https://github.com/paylivre/sdk-gateway-mobile-docs
